services:
  happy-farm:
    build: .
    image: happy-farm
    ports:
      - 6969:6969
    environment:
      - FARM_TICK_DURATION=120
      - FARM_FLAG_LIFETIME=120
      - FARM_SUBMIT_PERIOD=5
      - FARM_BATCH_LIMIT=100
      - FARM_FLAG_FORMAT=[a-zA-Z]{4}
      - FARM_TEAM_TOKEN="teamtoken"
      - FARM_SYSTEM_URL=${SYSTEM_URL}
      - FARM_SYSTEM_TYPE=${SYSTEM_TYPE}
      - FARM_TEAMS=10
      - FARM_PASSWORD=testtesttest
      - FARM_SECRET_KEY=${SECRET_KEY}
      - FARM_DEBUG=${DEBUG}
      - FARM_DATABASE=/happy-db/flags.db
      - FARM_HFI_CACHE=/hfi-bin
      - FARM_HFI_SOURCE=/hfi-src
    volumes:
      - happy-db:/happy-db
      - hfi-cache:/hfi-bin
volumes:
  happy-db:
  hfi-cache:
