services:
  happy-farm:
    build: .
    image: happy-farm
    ports:
      - 6969:6969
    environment:
      - FARM_TICK_DURATION=${TICK_DURATION}
      - FARM_FLAG_LIFETIME=${FLAG_LIFETIME}
      - FARM_SUBMIT_PERIOD=${SUBMIT_PERIOD}
      - FARM_BATCH_LIMIT=${BATCH_LIMIT}
      - FARM_FLAG_FORMAT=${FLAG_FORMAT}
      - FARM_TEAM_TOKEN=${TEAM_TOKEN}
      - FARM_SYSTEM_URL=${SYSTEM_URL}
      - FARM_TEAMS=${TEAMS}
      - FARM_PASSWORD=${PASSWORD}
      - FARM_SECRET_KEY=${SECRET_KEY}
      - FARM_DEBUG=${DEBUG}
      - FARM_DATABASE=/happy-db/flags.db
      - FARM_HFI_CACHE=/hfi-bin
      - FARM_HFI_SOURCE=/hfi-src
    volumes:
      - happy-db:/happy-db
      - hfi-cache:/hfi-bin
volumes:
  happy-db:
  hfi-cache:
